### ISSUE TITLE
It says I have to open an issue to get added

### ISSUE THREAD

**Issue by liebscher** [CodeReviewCommunity/CodeReviewCommunity.github.io#4]
And I would like added, please.

Hey guys, it's [AlexL](http://codereview.stackexchange.com/users/35559/alex-l). I have no idea what this CR GitHub is about but I'd like to join! I guess add me to the "web dev" team. Is there a place I can find out more about this project?

**Comment by nibroc** [comment]
Once upon a time, we had an idea in the chat room that we should post code on here for a few team projects and for a few examples of high quality projects for each language. Since that time, the group has gone pretty neglected. Maybe a meta CR post (or github issue) is in order to figure out what (if anything) is to be done with this (I would certainly love to collaborate with some people to make some example C or C++ projects if anyone is interested).

In the mean time, since the existing groups are language oriented, and the goal of the org is language oriented (I think...), I've gone ahead and created a PHP group and added you to it. 

I'll go ahead and leave this issue open for now in case anyone else has anything to adds or thinks I've chosen the wrong group name.

**Comment by liebscher** [comment]
Oh... Darn, I'll see about making a meta post about this. I certainly would love to collaborate with some of my CR peers!

**Comment by Zomis** [comment]
It does seem unfortunately that the "CR goes to github" operation has stalled. However, Code Review members are active on github and there are a couple of projects that are open for collaboration, it does not seem like the CodeReviewCommunity page is as active as we hoped it would be though. Hopefully, we can change that.

**Comment by rolfl** [comment]
complete.
